# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build:dev --if-present
#    - run: npm test
    - run: echo 1. generate diary.tar.gz
    - run: |
        rm -rf diary.tar.gz
        tar -zcvf diary.tar.gz __sapper__/
    - run: echo 2. JFrog upload
    - run: |
        curl -X PUT 'http://iinow.synology.me:9901/artifactory/diary/diary.tar.gz' \
          --header 'Authorization: Bearer '${{ secrets.ADMIN_TOKEN }} \
          --header 'Content-Type: application/gzip' \
          --data-binary '@diary.tar.gz'
    - run: |
        curl -w " - status code: %{http_code}" -X POST 'http://iinow.synology.me:9999/job/diary-web/build' \
          --header 'Authorization: Basic '${{ secrets.JENKINS_SEGEG_TOKEN }}
